# Autogenerated file
def render(*a, **d):
    yield """<!DOCTYPE html> <title>IoTMeter</title> <meta charset=UTF-8  /> <meta name=viewport  content=\"width=device-width, initial-scale=1\" /> <link href=\"main/static/style.css\" rel=stylesheet /> <script type=\"application/javascript\" src=\"main/static/loadLibrary.js\"></script> <body id=mainBody  style=\"background-color: black;\" onload=\"loadLibrary()\">"""
